version: 2.1
orbs:
  node: circleci/node@5
jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
      - run: npm install

  lint-code:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm install --no-save eslint
      - run: |
                 echo 'export default [
                   {
              files: ["**/*.js"],
              languageOptions: {
                ecmaVersion: "latest",
                sourceType: "module"
                     },
              env: {
                browser: true,
                node: true
                     },
                   }
                 ];' > eslint.config.js
      - run: npx eslint .  # Run ESLint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - install-dependencies
      - lint-code:
          requires:
            - install-dependencies

