version: 2.1
orbs:
  node: circleci/node@5

jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build dependencies
          command: echo "Building things..."
      - run:
          name: Install dependencies
          command: npm install

  lint-code:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install ESLint
          command: npm install --no-save eslint
      - run:
          name: Create ESLint config
          command: |
            echo 'export default [
              {
                files: ["**/*.js"],
                languageOptions: {
                  ecmaVersion: "latest",
                  sourceType: "module",
                  globals: {
                    browser: true,
                   
                },
              }
            ];' > eslint.config.js
      - run:
          name: Run ESLint
          command: npx eslint .  # Run ESLint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - install-dependencies
      - lint-code:
          requires:
            - install-dependencies
