version: 2.1
orbs:
  node: circleci/node@5
jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
      - run: npm install

  lint-code:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - install-dependencies
      - lint-code:
          requires:
            - install-dependencies

