version: 2.1
orbs:
  node: circleci/node@5

jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build dependencies
          command: echo "Building things..."
      - run:
          name: Install dependencies
          command: npm install

  lint-code:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm install --no-save eslint
      - run:
          name: Create ESLint config
          command: |
            echo 'export default [
              {
                files: ["**/*.js"],
                languageOptions: {
                  ecmaVersion: "latest",
                  sourceType: "module",
                  globals: {
                    browser: true,
                    node: true
                  }
                },
              }
            ];' > eslint.config.js
      - run:
          name: Run ESLint
          command: npx eslint .  # Run ESLint

  package-project:
    executor: node/default
    steps:
      - run: mkdir -p ./dist/build
      - run: echo "Packaged the file properly"

  unit-tests:
    executor: node/default
    steps:
      - run: echo "Marching through unit tests"

  integration-tests:
    executor: node/default
    steps:
      - run: echo "Marching through integration tests"

  regression-tests:
    executor: node/default
    steps:
      - run: echo "Marching through integration tests"

  performances-tests:
    executor: node/default
    steps:
      - run: echo "Marching through performances tests"

  security-tests:
    executor: node/default
    steps:
      - run: echo "Marching through security tests"

  compatibility-tests:
    executor: node/default
    steps:
      - run: echo "Marching through compatibility tests"

  accessibility-tests:
    executor: node/default
    steps:
      - run: echo "Marching through accessibility tests"

workflows:
  version: 2
  build-test:
    jobs:
      - install-dependencies
      - lint-code:
          requires:
            - install-dependencies
      - package-project:
          requires:
            - lint-code


      - unit-tests: &requires_package
          requires:
            - package-project
          filters:
            branches:
              only: develop
      - integration-tests:
          <<: *requires_package
      - regression-tests:
          <<: *requires_package
      - performances-tests:
          <<: *requires_package
      - security-tests:
          <<: *requires_package
      - compatibility-tests:
          <<: *requires_package
      - accessibility-tests:
          <<: *requires_package
